### ISSUE TITLE
AttributeError importing map piece flver m1000B0_0000

### ISSUE THREAD

**Issue by RustyOlDagger** [Grimrukh/soulstruct-blender#10]
When attempting to import map piece m1000B0_0000 (from Map Stem m15_00_00_00, Sen's Fortress), an error reading `Error: Python:` is shown. I've pasted the Blender console log below.

```
Saved settings to C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\GlobalSettings.json
# INFO: Importing map piece FLVER: C:\Games\Steam\steamapps\common\DARK SOULS REMASTERED\map\m15_00_00_00\m1000B0A15.flver.dcx
  ERROR :: soulstruct.base.base_binary_file         ::  110 :: Error occurred while reading `FLVER` from binary data. See traceback.
  ERROR :: soulstruct.base.base_binary_file         ::   87 :: Error occurred while reading `FLVER` with path 'C:\Games\Steam\steamapps\common\DARK SOULS REMASTERED\map\m15_00_00_00\m1000B0A15.flver.dcx'. See traceback.
CRITICAL :: 2023-11-04 22:32:20,069 :: soulstruct_havok               :: Line   77 :: Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 259, in execute
    flver = FLVER.from_path(flver_path)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\core.py", line 196, in from_path
    flver = super(FLVER, cls).from_path(path)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\base_binary_file.py", line 85, in from_path
    binary_file = cls.from_bytes(BinaryReader(path))
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\base_binary_file.py", line 107, in from_bytes
    binary_file = cls.from_reader(reader)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\core.py", line 148, in from_reader
    check_ds1_layouts(layouts, array_headers, submeshes)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\layout_repair.py", line 126, in check_ds1_layouts
    guessed_layout = guess_mtd_layout(mtd_name, member_unk_00, is_chr)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\layout_repair.py", line 94, in guess_mtd_layout
    mtd_info = MTDInfo.from_mtd_name(mtd_name)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\mtd.py", line 676, in from_mtd_name
    mtd_info.no_tangents = True
AttributeError: 'MTDInfo' object has no attribute 'no_tangents'
CRITICAL :: 2023-11-04 22:32:20,071 :: soulstruct_havok               :: Line   77 :: Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 259, in execute
    flver = FLVER.from_path(flver_path)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\core.py", line 196, in from_path
    flver = super(FLVER, cls).from_path(path)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\base_binary_file.py", line 85, in from_path
    binary_file = cls.from_bytes(BinaryReader(path))
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\base_binary_file.py", line 107, in from_bytes
    binary_file = cls.from_reader(reader)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\core.py", line 148, in from_reader
    check_ds1_layouts(layouts, array_headers, submeshes)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\layout_repair.py", line 126, in check_ds1_layouts
    guessed_layout = guess_mtd_layout(mtd_name, member_unk_00, is_chr)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\flver\layout_repair.py", line 94, in guess_mtd_layout
    mtd_info = MTDInfo.from_mtd_name(mtd_name)
  File "C:\Users\callu\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\modules\soulstruct\base\models\mtd.py", line 676, in from_mtd_name
    mtd_info.no_tangents = True
AttributeError: 'MTDInfo' object has no attribute 'no_tangents'
Info: Importing map piece FLVER: C:\Games\Steam\steamapps\common\DARK SOULS REMASTERED\map\m15_00_00_00\m1000B0A15.flver.dcx
Error: Python:
```

**Comment by RustyOlDagger** [comment]
Same issue when trying to import m7101B1_0000 from map m15_01_00_00 (Anor Londo).

**Comment by Grimrukh** [comment]
This is fixed in the version going up later today! Hang tight
