### ISSUE TITLE
FLVER Import "IndexError: list index out of range" for m14_00_00_00\m0208B0A14

### ISSUE THREAD

**Issue by Dynamic-src** [Grimrukh/soulstruct-blender#15]
More of the same, sadly :
```
 INFO: Importing map piece FLVER: G:\Steam\steamapps\common\DARK SOULS REMASTERED\map\m14_00_00_00\m0208B0A14.flver.dcx# INFO: Loaded 0 textures in 0.001 seconds.
WARNING :: soulstruct.base.models.flver.mesh_tools  ::  102 :: Submesh 1 has NaN vertex data and will be ignored by MergedMesh.
# INFO: Merged FLVER submeshes in 0.0202757999941241 s
# INFO: Created Blender mesh in 0.007567399996332824 s
Traceback (most recent call last):
  File "C:\Users\Dynamic\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 277, in execute
    bl_armature, bl_mesh = importer.import_flver(flver, name=bl_name, transform=transform)
  File "C:\Users\Dynamic\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 578, in import_flver
    bl_flver_mesh = self.create_flver_mesh(
  File "C:\Users\Dynamic\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 861, in create_flver_mesh
    bl_vert_bone_weights, bl_vert_bone_indices = self.create_bm_mesh(bl_mesh, merged_mesh)
  File "C:\Users\Dynamic\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 943, in create_bm_mesh
    loop_uv_data = merged_mesh.loop_uvs[i][valid_loop_indices].ravel()
IndexError: list index out of range
```

**Comment by Grimrukh** [comment]
Looks like more QLOC shenanigans, will investigate.

**Comment by Grimrukh** [comment]
This map piece should now be handled (and this error resolved more generally).
