### ISSUE TITLE
PTDE flver import error

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#29]
Tried importing m3200B1A15 from Anor Londo and got this error:

# INFO: Loaded 33 textures in 0.043 seconds.
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifSpcLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifSpcLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifSpcLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifSpcBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifSpcLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
# WARNING: Texture type 'g_DetailBumpmap' does not seem to be supported by shader 'FRPG_Phn_ColDifBmpLit.spx'. Creating FLVER material texture node anyway (with no UV input).
Traceback (most recent call last):
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct_lib\soulstruct\base\models\flver\mesh_tools.py", line 245, in build_stacked_loops
    loop_uvs_i = all_uv_layers.index(uv_layers[uv_i])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 150, in execute
    bl_armature, bl_mesh = importer.import_flver(flver, name=bl_name)
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 656, in import_flver
    bl_flver_mesh = self.create_flver_mesh(
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct\flver\import_flver.py", line 936, in create_flver_mesh
    merged_mesh = MergedMesh.from_flver(
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct_lib\soulstruct\base\models\flver\mesh_tools.py", line 125, in from_flver
    all_vertices, loop_data_dict = cls.build_stacked_loops(
  File "C:\Users\fromsoftserve\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_soulstruct_lib\soulstruct\base\models\flver\mesh_tools.py", line 248, in build_stacked_loops
    raise ValueError(
ValueError: FLVER submesh (MTD 'A15_Stainedglass[DSB]_Alp.mtd') UV layer index 1 is out of range of its detected UV layer list: ['UVMap1']. This is probably due to incorrect MTD parsing. Please report this bug on GitHub with the name of the FLVER model!

// thanks for all your hard work!

**Comment by Grimrukh** [comment]
Can confirm this old issue was fixed at some point!
