### ISSUE TITLE
Fails on Linux due to Windows DLL imports

### ISSUE THREAD

**Issue by Grimrukh** [Grimrukh/soulstruct-blender#8]
Need to make these optional.

**Comment by CocaineJohnsson** [comment]
Can confirm, relevant log output:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct/__init__.py", line 47, in <module>
    from io_soulstruct.flver import *
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct/flver/__init__.py", line 66, in <module>
    from io_soulstruct.misc_operators import CopyMeshSelectionOperator, CutMeshSelectionOperator
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct/misc_operators.py", line 11, in <module>
    from io_soulstruct.utilities.operators import LoggingOperator
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct/utilities/__init__.py", line 3, in <module>
    from .misc import *
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct/utilities/misc.py", line 27, in <module>
    from soulstruct.containers import Binder
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/__init__.py", line 7, in <module>
    from soulstruct.containers import Binder, EntryNotFoundError
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/containers/__init__.py", line 16, in <module>
    from .core import Binder, BinderVersion, BinderVersion4Info, BinderFlags, BinderError, EntryNotFoundError
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/containers/core.py", line 22, in <module>
    from soulstruct.base.base_binary_file import BaseBinaryFile
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/base/base_binary_file.py", line 14, in <module>
    from soulstruct.games import Game, get_game
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/games.py", line 28, in <module>
    from soulstruct.dcx import DCXType
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/dcx/__init__.py", line 1, in <module>
    from .core import DCXType, compress, decompress, is_dcx
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/dcx/core.py", line 24, in <module>
    from . import oodle
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/dcx/oodle.py", line 257, in <module>
    LOAD_DLL(str(_location))
  File "/home/cocaine/.config/blender/4.1/scripts/addons/io_soulstruct_lib/soulstruct/dcx/oodle.py", line 191, in LOAD_DLL
    __DLL = c.WinDLL(dll_path)  # uses `stdcall` convention, not `cdecl`
            ^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'WinDLL'
```
